### PR TITLE
Add bootstrap actions option

### PR DESCRIPTION
**Pull request by vanderGoes**
Can you give feedback on my approach? 

When I run the test I only get one issue: `.../sparksteps/sparksteps/cluster.py:33:1: C901 'emr_config' is too complex (11)` 

I think this is because of all the if statements.

Thanks!

### CODE REVIEW

**Comment by ksindi** [comment]
Nice @vanderGoes. Will give feedback today.

**Comment by ksindi** [comment]
@vanderGoes mind also removing `max-complexity=10` in the setup.cfg file? Travis is erroring because of it and I've been wanting to take that out anyway.

Everything looking good. Perhaps just confirm it works for your use case and I'll merge.

**Comment by vanderGoes** [comment]
Done. All tests passed/skipped.

**Comment by ksindi** [comment]
Awesome job! Just to confirm, did you get this to run live for your use case?

**Pull request merged**
